### ISSUE TITLE
Messing with bitcoin core wallet 

### ISSUE THREAD

**Issue by S5h4D3S** [NixPlatform/NixCore#1]
You cannot run on windows Bitcoin core wallet and NIX at the same time it's messing with directories

**Comment by phamels** [comment]
@S5h4D3S You can change the default directory NIX should use to store its data for now.

**Comment by S5h4D3S** [comment]
to late it started overwriting bitcoin directory :-( I did changed the directory problem is you cannot run NIX wallet and bitcoin core at the same time

**Comment by avrida** [comment]
If you have a BitcoinCore wallet installed, before you start NIX wallet, be sure to rename or backup the bitcoin blockchain folder "..\AppData Bitcoin"!

**Comment by mattt21** [comment]
patched in pos branch, will be updated soon.

**Comment by mattt21** [comment]
#10 updated
