### ISSUE TITLE
Does not compile under Arch Linux

### ISSUE THREAD

**Issue by BossHoggins** [NixPlatform/NixCore#17]
Options used to compile and link:
  with wallet   = yes
  with usbdevice  = no
  with gui / qt = yes
    qt version  = 5
    with qr     = yes
  with zmq      = yes
  with test     = no
  with bench    = no
  with upnp     = yes
  use asm       = yes
  debug enabled = no
  werror        = no

  target os     = linux
  build os      =

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-implicit-fallthrough
  LDFLAGS       =
  ARFLAGS       = cr

------------------------

  CXXLD    nixd
/usr/bin/ld: tor/src/common/libor-crypto.a(compress_zstd.o): in function `tor_zstd_get_version_str':
compress_zstd.c:(.text+0x55): undefined reference to `ZSTD_versionNumber'
/usr/bin/ld: tor/src/common/libor-crypto.a(compress_zstd.o): in function `tor_zstd_compress_new':
compress_zstd.c:(.text+0x1ab): undefined reference to `ZSTD_createCStream'
/usr/bin/ld: compress_zstd.c:(.text+0x1c2): undefined reference to `ZSTD_initCStream'
/usr/bin/ld: compress_zstd.c:(.text+0x1cd): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x232): undefined reference to `ZSTD_createDStream'
/usr/bin/ld: compress_zstd.c:(.text+0x246): undefined reference to `ZSTD_initDStream'
/usr/bin/ld: compress_zstd.c:(.text+0x251): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x25d): undefined reference to `ZSTD_getErrorName'
/usr/bin/ld: compress_zstd.c:(.text+0x287): undefined reference to `ZSTD_freeDStream'
/usr/bin/ld: compress_zstd.c:(.text+0x2ec): undefined reference to `ZSTD_getErrorName'
/usr/bin/ld: compress_zstd.c:(.text+0x316): undefined reference to `ZSTD_freeCStream'
/usr/bin/ld: tor/src/common/libor-crypto.a(compress_zstd.o): in function `tor_zstd_compress_process':
compress_zstd.c:(.text+0x47c): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x503): undefined reference to `ZSTD_decompressStream'
/usr/bin/ld: compress_zstd.c:(.text+0x521): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x559): undefined reference to `ZSTD_endStream'
/usr/bin/ld: compress_zstd.c:(.text+0x588): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x5bb): undefined reference to `ZSTD_compressStream'
/usr/bin/ld: compress_zstd.c:(.text+0x601): undefined reference to `ZSTD_flushStream'
/usr/bin/ld: compress_zstd.c:(.text+0x629): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x655): undefined reference to `ZSTD_isError'
/usr/bin/ld: compress_zstd.c:(.text+0x6bc): undefined reference to `ZSTD_getErrorName'
/usr/bin/ld: compress_zstd.c:(.text+0x764): undefined reference to `ZSTD_getErrorName'
/usr/bin/ld: compress_zstd.c:(.text+0x79c): undefined reference to `ZSTD_getErrorName'
/usr/bin/ld: tor/src/common/libor-crypto.a(compress_zstd.o): in function `tor_zstd_compress_free':
compress_zstd.c:(.text+0x828): undefined reference to `ZSTD_freeDStream'
/usr/bin/ld: compress_zstd.c:(.text+0x851): undefined reference to `ZSTD_freeCStream'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4542: nixd] Error 1
make[2]: Leaving directory '/usr/src/gits/NixCore/src'
make[1]: *** [Makefile:11205: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/gits/NixCore/src'
make: *** [Makefile:751: all-recursive] Error 1

**Comment by mattt21** [comment]
fixed in a56bc8f76057abab7fc87a18665382aef70d9500
