### ISSUE TITLE
Block height correct but stuck on Connecting to Peers v.2.1.1

### ISSUE THREAD

**Issue by unbelievable-jeff** [NixPlatform/NixCore#19]
N.B - report submitted on behalf of friend;

Fresh install of 2.1.1 - everything installed & synced correctly but wallet not been opened for couple of days - opened up and it's hanging on "Connecting to Peers - 23hrs behind". Current Block Height matches official explorer. Debug log littered with 'AcceptBlock FAILED'

Wallet also reported GNs require new start.  Restarted and status changes to expired.  Come out of wallet, go back into wallet and and it begins to sync then gets stuck at connecting to peers stage as mentioned above. Nodes status says Missing.

Wallet to synchronise with the network

![image](https://user-images.githubusercontent.com/43891495/49025890-81cdc480-f194-11e8-95ce-db2ca1aebcbd.png)

Keeps happening each time wallet is opened

2.1.1 from github

Windows 10/i3/ssd

[debug.zip](https://github.com/NixPlatform/NixCore/files/2616318/debug.zip)

**Comment by mattt21** [comment]
There seems to be a small edge case where zerocoin spend transactions are not getting rolled back properly when blocks are transmitted from peers out of order. It is being looked into. For now, restoring the chainfiles and syncing from scratch is the temp solution.

**Comment by unbelievable-jeff** [comment]
The QT was installed from scratch a few times with chain getting deleted beforehand, no luck. Resolved with bootstrap
