### ISSUE TITLE
Error compiling on ubuntu 16.04

### ISSUE THREAD

**Issue by electron64** [NixPlatform/NixCore#2]
Hello i get that error while compiling :

```/usr/bin/ld: crypto/libnix_crypto.a(crypto_libnix_crypto_a-Sponge.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
crypto/libnix_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:4086: recipe for target 'nixd' failed
make[2]: *** [nixd] Error 1
make[2]: Leaving directory '/home/dev/NixCore/src'
Makefile:10698: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dev/NixCore/src'
Makefile:752: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by electron64** [comment]
Hi, i tried but i get an other error.
`libnix_util.a(libnix_util_a-utiltime.o): In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:243: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
Makefile:4086 : la recette pour la cible « nixd » a échouée
make[2]: *** [nixd] Erreur 1
make[2] : on quitte le répertoire « /home/nono/Bureau/NixCore/src »
Makefile:10698 : la recette pour la cible « all-recursive » a échouée
make[1]: *** [all-recursive] Erreur 1
make[1] : on quitte le répertoire « /home/nono/Bureau/NixCore/src »
Makefile:752 : la recette pour la cible « all-recursive » a échouée
make: *** [all-recursive] Erreur 1`

**Comment by cryptosharks131** [comment]
Make sure you are compiling in Ubuntu and inside the source code folder.

make clean
./autogen.sh
./configure --without-gui
make

Hope this helps.
