### ISSUE TITLE
LPOS duplicating - wallet balances being returned to full stake amount. 

### ISSUE THREAD

**Issue by Daschesc** [NixPlatform/NixCore#22]
LPOS Staked coins receive stake and generate a new contract, yet show old amount in LPOS window. 
At the same time, the (windows) wallet shows a balance showing the new contract amount (post stake received) 

I expect to see a single contract tab, with the contract stake received with only the contract(s) I have issued with my Nix Coins. 

There should only be 1 contract. stake received adjusted amount and created new contract. 

https://www.dropbox.com/s/qftdl39dhq9uugf/LPOSbug.jpg?dl=0
https://www.dropbox.com/s/mbzywliaiepwg6g/LPOSbugbalancewrong.jpg?dl=0

AS reliable as staking occurs. 

Using the latest version of the wallet per $nix discord (userid @dasche)

I have always found staking on this wallet to "change balances" beyond the actual balances. causes issues with balances when doing transactions, abandoned transactions occur often. 

[debug.log](https://github.com/NixPlatform/NixCore/files/2730871/debug.log)

**Comment by mattt21** [comment]
GUI updating issue is resolved in 2.3.0.

**Comment by Yazanarki** [comment]
Great team , diligent in addressing and finding solutions for issues.
