### ISSUE TITLE
LPoS contracts possibly failing due to space before or after reward address

### ISSUE THREAD

**Issue by BossHoggins** [NixPlatform/NixCore#23]
LPoS contract failed to stake due to a reward address mismatch.  Customer sent me screenshots of the active contract and everything looked fine.  Advised them to cancel and recreate the contract being very careful not to include any extra spaces before or after the reward address.

New contract successfully stakes.
It's unknown exactly what caused the error, but this is my best guess.

**Comment by BossHoggins** [comment]
new information:
it appears that it is something else with the CheckProofOfStake concerning the foundFeeAddress. I hit another failed stake with the error "CheckProofOfStake: foundFeeAddress-failed" but have no new contracts that haven't already gotten a stake and wallet config is unchanged.

**Comment by mattt21** [comment]
CheckProofOfStake: foundFeeAddress-failed will return if the contract is not paying out correctly, are you using the latest release? And if so, how many of your contracts are having this issue?

**Comment by BossHoggins** [comment]
On closer examination of the errors in the log, it seems I was incorrect with my original report. Given the nature of the error, I assumed it was a contract that had yet to catch its first stake. I'm sorry, I should have realized this earlier.

It is now clear to me that both errors actually happened on a single contract whose amount has been automatically split into 2 due to its size.

I am using the latest release, 2.2.0.1

**Comment by mattt21** [comment]
So the contract hit a stake and split the utxo into 2 separate contracts, and the current 2 contracts are pulling this issue?

**Comment by BossHoggins** [comment]
Correct. 

And just be clear, both utxo's continue to successfully stake without any intervention on my part, such as a wallet restart. The first error happened directly after the split, the 2nd happened 7 days later.

**Comment by mattt21** [comment]
"both utxo's continue to successfully stake without any intervention on my part, such as a wallet restart. The first error happened directly after the split, the 2nd happened 7 days later." Ok, so you are hitting stakes with it? Just inconsistent error logging?

**Comment by mattt21** [comment]
@BossHoggins this is fixed in 2.3.0. Will be released soon.
