### ISSUE TITLE
NIXd stops accepting RPC or CLI commands

### ISSUE THREAD

**Issue by MNPJason** [NixPlatform/NixCore#24]
Server Infomation
Ubuntu 16.04.6 LTS
24-Core
144GB Ram
6TB HD

(Only Wallet Running on Server)

Wallet Info
`NIX Core version v2.3.0.1-0654ed8 (release build)`

Started wallet at `2019-03-25 22:21:36 `
At `2019-03-26 02:25:01` Started receiving
` WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting`

Running JSON RPC cronJob Commands every 60 seconds and 1 every 5 min
60 second Commands
`getblockchaininfo`
`getnetworkinfo`
`getwalletinfo`
`ghostnode count enabled`

(multi times depending on how many blocks passed in the last 60 seconds)
`getblockhash`
`getblock`

5 min Command
`ghostnodelist full`

**Comment by mattt21** [comment]
Removed dependency on chainactive for issynced method which required cs_main lock (which was not locking cs_main in the first place) in f22ffcc. Try building from master and replicating your issues.

**Comment by mattt21** [comment]
No response from @MNPJason.
Tag v2.3.0.2 is released with the fix.

**Comment by tlghnb** [comment]
@mattt21 This issue still persists with the version 3.0.
