### ISSUE TITLE
NIX Sigma 3.0rc2 10 ghosted Nix left unconfirmed for several hours

### ISSUE THREAD

**Issue by Knightofthebooks** [NixPlatform/NixCore#28]
Debug log sended via nixplatform website.

Problem: 10 ghosted Nix left unconfirmed for several hours (ca. 8 hours) although all ghost vault transactions that were made after were confirmed. 
Abandoning was not possible during that time. 
Again later the ghosted Nix suddenly showed up as confirmed. 
After unghosting these 10 Nix the Ghost Vault showed 0.6 remaining Nix (should have been zero Nix). 
Which means that the number that showed up in the ghost vault was not correct (should have been 10.6 Nix and not 10.0 Nix) 
or 
that 0.6 ghosted Nix were created somehow.

**Comment by mattt21** [comment]
fixed
