### ISSUE TITLE
NIX Sigma 3.0rc2 ghosting with more than one decimal places

### ISSUE THREAD

**Issue by Knightofthebooks** [NixPlatform/NixCore#30]
When trying to ghost a number of nix that has more than one decimal places there appears following warning: "You cannot ghost NIX at the moment. Please check the debug log for errors."

This warning could be replaced i.e.: "You can ghost a number of NIX with one decimal place, i.e.: 5.1 NIX"

Or no warning appears and wallet hangs up.

![crashes when unghosting more than on decimal nix](https://user-images.githubusercontent.com/50663678/57856081-8773a100-77ec-11e9-9081-e607e4bbb20a.jpg)

**Comment by Knightofthebooks** [comment]
![you cannot ghost atm](https://user-images.githubusercontent.com/50663678/57928396-e69ae980-78b0-11e9-9509-dcd6496166b4.jpg)

**Comment by Knightofthebooks** [comment]
It seems that the wallet hangs up when not unghosting exactly the same number of Nix that was ghosted earlier.

![crash when unghosting a number that is not available in the ghostvault](https://user-images.githubusercontent.com/50663678/57929041-8d33ba00-78b2-11e9-93dc-039c5e327665.jpg)

Debug log:
[debug nix 3.log](https://github.com/NixPlatform/NixCore/files/3191515/debug.nix.3.log)

**Comment by mattt21** [comment]
fixed #33
