### ISSUE TITLE
NIX Sigma 3.0rc2 ghosting and unghosting issues and wallet hangs up

### ISSUE THREAD

**Issue by Knightofthebooks** [NixPlatform/NixCore#32]
1.) Ghosted 555.5 Nix and unghosted it. After two hours still no confirmation of the transaction. Abandoning transaction is possible. 

2.) Unghosting again 555 Nix and 0.5 Nix. Wallet hangs up for a few seconds after pushing the "Un-ghost NIX" button.

3.) Although the unghosted Nix are unconfirmed the Ghost Vault shows zero Nix.
This time abandoning transaction is not possible (at least atm).

4.) After closing and restarting wallet 555.5 Nix show up again in the Ghost Vault as ghosted. Abandoning of unghosting transaction still not possible.

**Comment by mattt21** [comment]
Your descriptions need to be more detailed - and more importantly need to have your debug.log attached. A lot of these issues you are reporting are not easily duplicable.

**Comment by Knightofthebooks** [comment]
I've sended the first debug.log via website.
