### ISSUE TITLE
NIX Sigma 3.0rc2 - Undesired unghosting behaviour

### ISSUE THREAD

**Issue by unbelievable-jeff** [NixPlatform/NixCore#33]
Wallet sometimes crashes when attempting to unghost

Error message if Un-ghost amount entered isn't possible

Hang/crash
![image](https://user-images.githubusercontent.com/43891495/57807520-38306080-7759-11e9-973e-283888c1337b.png)

Every time - steps:
Ghost a single denomination 
Try to unghost partially

W10 x64 

[debug.log](https://github.com/NixPlatform/NixCore/files/3184352/debug.log)

**Comment by mattt21** [comment]
Fixed in 7b8db77bab9f8b03bc5bdbf27e2ad14804d28532.
