### ISSUE TITLE
NIX Sigma 3.0rc2 After reindexing 

### ISSUE THREAD

**Issue by Knightofthebooks** [NixPlatform/NixCore#34]
Debug log attached below.

Issue: After reindexing (deleting chainstate and blocks folder) a wrong amount of ghosted nix appears. Should be 5000 ghosted Nix not 27422.1 Nix.

After closing wallet and restarting it the correct amount shows up.

![2 anzahl ghosted nix zu hoch](https://user-images.githubusercontent.com/50663678/57824785-8dda2c80-779c-11e9-8738-d82d869fb203.jpg)

![anzahl ghosted nix zu hoch](https://user-images.githubusercontent.com/50663678/57824832-b2360900-779c-11e9-8ef0-5dc9f7c5a3b4.jpg)

debug.log

[nix debug.log](https://github.com/NixPlatform/NixCore/files/3185308/nix.debug.log)

**Comment by mattt21** [comment]
fixed
