### ISSUE TITLE
Where can I see NIX wallet logs on Mac

### ISSUE THREAD

**Issue by devender-yadav** [NixPlatform/NixCore#4]
The wallet is showing **`Loading wallet...`** since last few hours. 

Where can I see logs on my mac os?

**Comment by mattt21** [comment]
~/Library/Application Support/nix will show you the debug file.

**Comment by devender-yadav** [comment]
@mattt21 its ~/Library/Application Support/Bitcoin 
I think at least name should be changed ;)

**Comment by mattt21** [comment]
@devender-yadav the directory is actually ~/Library/Application Support/nix. QT configuration is messing with the last known location for a qt wallet whether its for NIX or Bitcoin, something we are looking into.

https://github.com/NixPlatform/NixCore/blob/master/src/util.cpp#L638
