### ISSUE TITLE
ERROR: ProcessNewBlock: AcceptBlock FAILED (Transaction check failed (tx hash d14522db4b7d4cacd1c4c3982b6a71ab74f5d8ea72be87405170d2b6f640789c) )

### ISSUE THREAD

**Issue by stintel** [NixPlatform/NixCore#44]
3.0.1 is stuck at `37 week(s) behind`, tried `-rescan`, `-reindex`, even deleted `~/.nix/{blocks,chainstate}` but it keeps getting stuck. The debug.log is flooded with this line:
```
2019-06-04 08:55:34 ERROR: ProcessNewBlock: AcceptBlock FAILED (Transaction check failed (tx hash d14522db4b7d4cacd1c4c3982b6a71ab74f5d8ea72be87405170d2b6f640789c) )
```

getblockchaininfo:
```json
{
  "chain": "main",
  "blocks": 53032,
  "headers": 230440,
  "bestblockhash": "111fc7ff438c9f5f5e578f5165d8627a037a0f7394afd9d8f2603de2283f690c",
  "difficulty": 294221.0252640576,
  "mediantime": 1536780832,
  "verificationprogress": 0.2802159764612827,
  "initialblockdownload": true,
  "chainwork": "0000000000000000000000000000000000000000000000002267da98578cca63",
  "size_on_disk": 61931819,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1462060800,
      "timeout": 1530415442,
      "since": 6
    },
    "segwit": {
      "status": "active",
      "startTime": 1479168000,
      "timeout": 1530415442,
      "since": 6
    }
  },
  "warnings": ""
}
```

**Comment by mattt21** [comment]
@stintel are you building from the tag, or using gitians?

**Comment by stintel** [comment]
Building from https://github.com/NixPlatform/NixCore/archive/v3.0.1.tar.gz which apparently changed since I built. Once a release tarball was published it should never be changed anymore. If changes are needed, a new release should be made.

**Comment by mattt21** [comment]
Build from current tag and reindex. Older tag has issues and was not production ready.

**Comment by stintel** [comment]
It works after rebuilding the "new" 3.0.1. But please, don't do this in the future. If a release is bad it's bad. Accidents happen. You should have tagged 3.0.2 or 3.0.1.1 instead of "rewriting history". This is a nightmare for package maintainers.

**Comment by mattt21** [comment]
Agreed. An issue on our behalf. Apologies for the inconvenience!

**Comment by stintel** [comment]
No worries. Glad we're on the same page!
