### ISSUE TITLE
Vault to vault txs appear on chain but not showing in receiving wallet.

### ISSUE THREAD

**Issue by Beekers-McCluer** [NixPlatform/NixCore#47]
the following transaction was attempted between 2 separate machines. Previous attempts include doing various combinations of host to guest virtual machines, sending between 2 different wallet.dats using the same machine, and sending to other users. In all cases, tx's appear on chain but is never shown in receiving wallets.

---- Exact steps used ----
Receiving wallet:
linux precompiled binary, v3.0.4.0-eb50c82, 64bit
1. create new wallet.dat
2. encrypt wallet.dat, restart
3. generate default 10 ghost key

Sending wallet:
windows10 precompiled binary, v3.0.4.0-eb50c82, 64bit
1. create wallet.dat
2. encrypt wallet.dat, restart
3. received 1 NIX to "N" address. txid: 3c0bc2253093334255b0d7ecd166ee4eb22ecd8f74baf4f58d28661314b13621
4. ghost 0.2 NIX to self. txid: 3e57dcc1de4b1a94171e488020414a3d203c8e6068b64e9a8341e975aea15c05
5. using unghost nix from vault tab, deselect un-ghost to myself,  enter and verify receiving wallet ghost key.
6. send 0.1 ghosted NIX. txid: 133e9c8de1b6a0e14b618de46b04da4ea561af3087a55c7dafc6a7b771589ca1

Receiving wallet fails to display ghosted NIX. Attempts to unghost expected amount to self fails. No related errors in debug.log

**Comment by dacx** [comment]
Did you try displaying and/or un-ghosting via the console? If so, we can narrow it down to a visual bug.

**Comment by Beekers-McCluer** [comment]
Yes, I have. Console shows no ghost_vault balance and attempts to unghost expected amounts returns the same error as the qt popup window, "Closest amount you can send: -0.000000, -0.000000"

**Comment by mattt21** [comment]
Fixed with d69bf16d243b5776c5d589ebd46afd863cf6eb03
