### ISSUE TITLE
Problem sending any transaction - 2 hours and nothing

### ISSUE THREAD

**Issue by S5h4D3S** [NixPlatform/NixCore#5]
I can receive transactions, but i cannot send any amounth out.  0/unconfirmed, in memory pool, broadcast through 7 nodes.

Windows wallet - Recomended fee
I was waiting 2 hours and nothing

**Comment by avrida** [comment]
Same problem. I can not send any transactions. I tried to put different commissions up to 1NIX per kilobyte.

**Comment by S5h4D3S** [comment]
finally tx came through it took 3 hours

**Comment by avrida** [comment]
The problem is the place to be! Outgoing transactions from the NIX Windows wallet do not work (v.1.0.1)!

**Comment by S5h4D3S** [comment]
Status: 0/unconfirmed, in memory pool, broadcast through 21 nodes
Date: 29/06/2018 22:27 now it 1:18 and transaction didn't came through v.1.0.1

**Comment by mattt21** [comment]
Update 1.0.2 fixes transaction broadcast issues fully.
