### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by bigwest60** [NixPlatform/NixCore#9]
Mac install puts config files in the Downloads folder.  Does not ask upon initial run where to put data files. 

RESOLVED (sort of):  Nix was conflicting with Bitcoin Core install.  I restored defaults and is now OK.  Except now Nix and Bitcoin wallets conflict.

**Comment by mattt21** [comment]
patched in pos branch, will be updated soon.

**Comment by mattt21** [comment]
#10 updated
